export default {
  sidebarWidth: '32%',
  sidebarWidthTablet: '52px',
  deviceWidthDesktop: '360px',
  drawerWidthDesktop: '260px',
  drawerWidthTablet: '320px',
  drawerHeightPhone: '250px',
  filterFormWidth: '160px',
  eventsDrawerWidth: '320px',
  bottomBarHeight: 56,
  popupMapOffset: 300,
  popupMaxWidth: 360,
  popupImageHeight: 144,
  cardContentMaxHeight: '40vh',
  qrCodeSize: 192,
};
